apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beepfront-preprod
  namespace: argocd
  labels:
    argocd.argoproj.io/instance: argocd
spec:
  destination:
    name: in-cluster
    namespace: beep-preprod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  project: beep-preprod
  source:
    path: front
    repoURL: https://github.com/Courtcircuits/beep-charts
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
        - values-preprod.yaml
