apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: beep-preprod
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: ArgoCD project for the preprod environment of the beep project
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
    - https://gitlab.polytech.umontpellier.fr/beep/voice/charts
    - https://github.com/Courtcircuits/beep-charts
    - https://charts.external-secrets.io
    - https://helm.traefik.io/traefik
    - https://charts.jetstack.io