apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-svc" .Values.appName | trunc 63 }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  - name: ws
    protocol: TCP
    port: {{ .Values.service.wsExternalPort }}
    targetPort: {{ .Values.service.wsInternalPort }}
  selector:
    app: {{ .Values.appName }}